# Generated by Django 5.0.2 on 2024-03-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0003_remove_device_device_role_remove_device_device_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
