# Generated by Django 5.0.4 on 2024-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='Status',
            field=models.CharField(default='VotreValeurParDéfaut', max_length=255),
        ),
    ]
