# Generated by Django 5.0.4 on 2024-08-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_management', '0011_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=['defauldf'], max_length=30),
            preserve_default=False,
        ),
    ]
